<?php

namespace Database\Seeders;

use App\Models\Branch;
use Illuminate\Database\Seeder;

class BranchSeeder extends Seeder
{
    public function run(): void
    {
        $branches = [
            [
                'code' => 'JKT001',
                'name' => 'Cabang Jakarta Pusat',
                'phone' => '02112345678',
                'email' => 'jakarta@buatserba.com',
                'province_id' => 6,
                'province_name' => 'DKI Jakarta',
                'city_id' => 151,
                'city_name' => 'Jakarta Pusat',
                'city_type' => 'Kota',
                'postal_code' => '10110',
                'full_address' => 'Jl. Sudirman No. 123, Jakarta Pusat',
                'is_active' => true,
                'priority' => 1,
            ],
            [
                'code' => 'BDG001',
                'name' => 'Cabang Bandung',
                'phone' => '02287654321',
                'email' => 'bandung@buatserba.com',
                'province_id' => 9,
                'province_name' => 'Jawa Barat',
                'city_id' => 23,
                'city_name' => 'Bandung',
                'city_type' => 'Kota',
                'postal_code' => '40111',
                'full_address' => 'Jl. Dago No. 456, Bandung',
                'is_active' => true,
                'priority' => 2,
            ],
            [
                'code' => 'SBY001',
                'name' => 'Cabang Surabaya',
                'phone' => '03198765432',
                'email' => 'surabaya@buatserba.com',
                'province_id' => 11,
                'province_name' => 'Jawa Timur',
                'city_id' => 444,
                'city_name' => 'Surabaya',
                'city_type' => 'Kota',
                'postal_code' => '60111',
                'full_address' => 'Jl. Tunjungan No. 789, Surabaya',
                'is_active' => true,
                'priority' => 3,
            ],
            [
                'code' => 'YGY001',
                'name' => 'Cabang Yogyakarta',
                'phone' => '02745678901',
                'email' => 'yogya@buatserba.com',
                'province_id' => 5,
                'province_name' => 'DI Yogyakarta',
                'city_id' => 501,
                'city_name' => 'Yogyakarta',
                'city_type' => 'Kota',
                'postal_code' => '55111',
                'full_address' => 'Jl. Malioboro No. 101, Yogyakarta',
                'is_active' => true,
                'priority' => 4,
            ],
            [
                'code' => 'MDN001',
                'name' => 'Cabang Medan',
                'phone' => '06156789012',
                'email' => 'medan@buatserba.com',
                'province_id' => 12,
                'province_name' => 'Sumatera Utara',
                'city_id' => 151,
                'city_name' => 'Medan',
                'city_type' => 'Kota',
                'postal_code' => '20111',
                'full_address' => 'Jl. Gatot Subroto No. 202, Medan',
                'is_active' => true,
                'priority' => 5,
            ],
            [
                'code' => 'MKS001',
                'name' => 'Cabang Makassar',
                'phone' => '04167890123',
                'email' => 'makassar@buatserba.com',
                'province_id' => 26,
                'province_name' => 'Sulawesi Selatan',
                'city_id' => 397,
                'city_name' => 'Makassar',
                'city_type' => 'Kota',
                'postal_code' => '90111',
                'full_address' => 'Jl. Ahmad Yani No. 303, Makassar',
                'is_active' => true,
                'priority' => 6,
            ],
            [
                'code' => 'DPS001',
                'name' => 'Cabang Denpasar',
                'phone' => '03678901234',
                'email' => 'denpasar@buatserba.com',
                'province_id' => 1,
                'province_name' => 'Bali',
                'city_id' => 114,
                'city_name' => 'Denpasar',
                'city_type' => 'Kota',
                'postal_code' => '80111',
                'full_address' => 'Jl. Sunset Road No. 404, Denpasar',
                'is_active' => true,
                'priority' => 7,
            ],
            [
                'code' => 'SMG001',
                'name' => 'Cabang Semarang',
                'phone' => '02489012345',
                'email' => 'semarang@buatserba.com',
                'province_id' => 10,
                'province_name' => 'Jawa Tengah',
                'city_id' => 232,
                'city_name' => 'Semarang',
                'city_type' => 'Kota',
                'postal_code' => '50111',
                'full_address' => 'Jl. Pemuda No. 505, Semarang',
                'is_active' => true,
                'priority' => 8,
            ],
            [
                'code' => 'PLG001',
                'name' => 'Cabang Palembang',
                'phone' => '07190123456',
                'email' => 'palembang@buatserba.com',
                'province_id' => 32,
                'province_name' => 'Sumatera Selatan',
                'city_id' => 350,
                'city_name' => 'Palembang',
                'city_type' => 'Kota',
                'postal_code' => '30111',
                'full_address' => 'Jl. Sudirman No. 606, Palembang',
                'is_active' => true,
                'priority' => 9,
            ],
            [
                'code' => 'BTM001',
                'name' => 'Cabang Batam',
                'phone' => '07781234567',
                'email' => 'batam@buatserba.com',
                'province_id' => 21,
                'province_name' => 'Kepulauan Riau',
                'city_id' => 38,
                'city_name' => 'Batam',
                'city_type' => 'Kota',
                'postal_code' => '29411',
                'full_address' => 'Jl. Engku Putri No. 707, Batam',
                'is_active' => true,
                'priority' => 10,
            ],
        ];

        foreach ($branches as $branch) {
            Branch::create($branch);
        }
    }
}
